version: 2.1

executors:
  node:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12

jobs:
  checkout_code:
    executor: node
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  test:
    executor: node
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies with npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm test
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules

  release:
    executor: node
    steps:
      - attach_workspace:
          at: ~/repo
      - checkout
      - run: npm run semantic-release

workflows:
  build:
    jobs:
      - checkout_code
      - test:
          requires:
            - checkout_code
      - release:
          context: org-global
          requires:
            - test
